### ISSUE TITLE
Issues of training both instance contrast and index contrast

### ISSUE THREAD

**Issue by tulilin** [pUmpKin-Co/offical-IndexNet#4]
Hello, I appreciate your work and I have read your code. For self-supervised pretraining, either instance contrast or index contrast is trained in the code in my understanding. Is there code implementation of training both instance contrast and index contrast? And for implementation, are MLPs in instance contrast and ConvMLPs in index contrast weight-sharing?
I am looking forward to your reply. Thank you!

**Comment by pUmpKin-Co** [comment]
Hi~I'm feel so sorry for my mistake. I miss the glboal branch (instance contrast) in the first released commit. I have added the possible implementation of training both instance contrast and index contrast in `IndexNetModel/IndexNetContrastMo.py` and `trainer.py`.

Moreover, the MLPs in instance contrast and ConvMLPs in index contrast  are not weight-sharing (see `IndexNetModel/IndexNetContrastMo.py`). 

Thank you for your interest to our work, more questions on the implementation are welcome !
