### ISSUE TITLE
How to train in LoveDA

### ISSUE THREAD

**Issue by YonghuiTAN22** [pUmpKin-Co/offical-IndexNet#5]

**Comment by pUmpKin-Co** [comment]
Hi~The implementation of LoveDA datasets is located in `dataset/dataset.py`.
You only need to change the potsdam dataset to LoveDA dataset in the main training file.
Thanks!

**Comment by pUmpKin-Co** [comment]
Closed as long periods of inactivity, feel free to reopen if there is any problem.
